---
- hosts: websever
  tasks:
      
    - name: login to jfrog
      shell: docker login -u kushal -p Kushal@123 kushalan.jfrog.io    
    
    - name: pull an image
      shell: docker pull kushalan.jfrog.io/artifactory/test/devops_practice:{{ BUILD_NUMBER }}

    - name: remove container
      shell: docker rm -f devopsAppDeploy
        
    - name: create a application container
      shell: docker run -id --name devopsAppDeploy -p 8111:8080 kushalan.jfrog.io/artifactory/test/devops_practice:{{ BUILD_NUMBER }}

 
   
